build:
  contextDir: null
  enabled: true
  env: null
  imageStreamTag:
    name: dotnet:3.1
    namespace: openshift
    useReleaseNamespace: false
  output:
    kind: ImageStreamTag
    pushSecret: null
  pullSecret: null
  ref: main
  resources: null
  startupProject: app
  uri: https://github.com/vishnutejakoya1/sample_crud
deploy:
  applicationProperties:
    enabled: false
    mountPath: /deployments/config/
    properties: '## Properties go here'
  env: null
  envFrom: null
  extraContainers: null
  initContainers: null
  livenessProbe:
    tcpSocket:
      port: http
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  readinessProbe:
    httpGet:
      path: /
      port: http
  replicas: 1
  resources: null
  route:
    enabled: true
    targetPort: http
    tls:
      caCertificate: null
      certificate: null
      destinationCACertificate: null
      enabled: true
      insecureEdgeTerminationPolicy: Redirect
      key: null
      termination: edge
  serviceType: ClusterIP
  volumeMounts: null
  volumes: null
global:
  nameOverride: null
image:
  name: null
  tag: latest